spring:
  application:
    name: sb01-hrbank-team10
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank_user
    password: hrbank1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs     # OpenAPI ???? ????? ??
  default-consumes-media-type: application/json   # ?? ?? Content-Type
  default-produces-media-type: application/json   # ?? ?? Content-Type
  swagger-ui:
    operations-sorter: alpha    # API ??? ??? ? ??
    tags-sorter: alpha          # API ?? ??? ? ??
    path: /swagger-ui
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true

backup:
  schedule:
    rate: 3600000  # 1시간(3600000ms)마다 실행
  worker:
    identifier:SYSTEM