spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        serverTimezone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:                               # PostgreSQL에서 날짜/시간 타입 변환 처리를 위한 설정
          time_zone=UTC:
          .lob:
            non_contextual_creation=true:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true


