spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_RAILWAY_PRIVATE_DOMAIN}:${PGPORT}/${POSTGRES_DB}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      data-source-properties:
        serverTimezone: Asia/Seoul
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect