spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${RAILWAY_PRIVATE_DOMAIN}:${PGPORT}/${POSTGRES_DB}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      data-source-properties:
        serverTimezone: Asia/Seoul